### ISSUE TITLE
Can not import global array from ga4py

### ISSUE THREAD

**Issue by mkhoshle** [GlobalArrays/ga4py#1]
Hello,

I need to use global array for python and I installed it and I am able to import it. 
But when I do 
```
In [3]: from ga4py import ga
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-61f189220ed6> in <module>()
----> 1 from ga4py import ga

ImportError: cannot import name ga
```
Does anyone know what is the reason?

**Comment by jeffdaily** [comment]
I haven't seen this error before.  Is there any way to get a more detailed error message?  Could I also have more information about your hardware/software environment and how you configured and build GA?

**Comment by jeffdaily** [comment]
The following worked for me on my macbook, though I imagine it would work similarly elsewhere.

I installed gfortran via homebrew.  I installed mpich-3.2.  I installed GA using the options `--disable-static --enable-shared` to produce a shared library for GA.  I ran `make` and `make install` and added the installation prefix to my `$PATH`.  Doing so puts the `ga-config` script in my `$PATH` so that the ga4py setup.py can use it to determine compiler and linker flags.  I built ga4py using `python setup.py build`.  This invoked cython to create the wrappers and build the extension module.  I did `python setup.py install --prefix=...` and set an appropriate install prefix.  I added the $prefix/lib/python2.7/site-packages install prefix to my PYTHONPATH.

To run, I found I had to `from mpi4py import MPI` before I could `from ga4py import ga`.  Otherwise GA was terminating with an error that MPI had not yet been initialized.

I hope that helps.  Please let me know.  Thanks!

**Comment by mkhoshle** [comment]
@jeffdaily Thanks. Here is what I do:
```
conda create -n openmpi python=2.7
pip install mdanalysis
conda install cython mpi4py 
./configure --prefix=/home/mkhoshle/app/ga/5.6.1/gcc485/openmpi-1.8.5-gnu-stock/ --disable-static --enable-shared
make -j 4
make install 
```
and then for `ga4py` I  do:

```
module load openmpi/1.8.5-gnu-stock
python setup.py build
python setup.py install --prefix=/home/mkhoshle/app/ga/5.6.1/gcc485/openmpi-1.8.5-gnu-stock/
```
after all these when I open ipython and do `from mpi4py import MPI` which is fine but then when I try to do `from ga4py import ga` I am getting the import error!

**Comment by mkhoshle** [comment]
Also here is the output of `echo $PYTHONPATH`:
```
/home/mkhoshle/miniconda2/lib/python2.7
```
I also added the following lines to ~/.bash_profile
```
PYTHONPATH=/home/mkhoshle/miniconda2/lib/python2.7
export PYTHONPATH

PYTHONPATH=$PYTHONPATH:/home/mkhoshle/ga4py
export PYTHONPATH
```
and here is the output of 'sys.path':
```
'',
 '/home/mkhoshle/miniconda2/bin',
 '/home/mkhoshle/miniconda2/lib/python2.7',
 '/home/mkhoshle/ga4py',
 '/home/mkhoshle/miniconda2/lib/python27.zip',
 '/home/mkhoshle/miniconda2/lib/python2.7/plat-linux2',
 '/home/mkhoshle/miniconda2/lib/python2.7/lib-tk',
 '/home/mkhoshle/miniconda2/lib/python2.7/lib-old',
 '/home/mkhoshle/miniconda2/lib/python2.7/lib-dynload',
 '/home/mkhoshle/miniconda2/lib/python2.7/site-packages/GridDataFormats-0.3.3-py2.7.egg',
 '/home/mkhoshle/miniconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg',
 '/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tempdir-0.7.1-py2.7.egg',
 '/home/mkhoshle/miniconda2/lib/python2.7/site-packages',
 '/home/mkhoshle/miniconda2/lib/python2.7/site-packages/IPython/extensions',
 '/home/mkhoshle/.ipython'
```

**Comment by jeffdaily** [comment]
Are you on a linux system or mac?  Also, did you build openmpi yourself or is it being provided by a package manager?  I noticed the `module load openmpi/1.8.5-gnu-stock`.

I tried installing openmpi on my mac using `conda install openmpi` and it seemed to install 1.6.3.  But I am not able to configure GA using this version of openmpi.  It tries to test the mpicc compiler but is getting an error `dyld: Library not loaded: @rpath/libmpi.1.dylib`.

**Comment by mkhoshle** [comment]
I am using a linux system! I did not build it myself and it is being provided by package manager. So which version of openmpi do I need to use in order to get this to work?

**Comment by mkhoshle** [comment]
@jeffdaily I think previously my path was kind of messed up and python was not able to find module ga. I am able to find ga now but when I do `from ga4py import ga` I get the following error!
```
In [2]: from ga4py import ga
python: ../../comex/src-mpi/comex.c:1377: comex_init: Assertion `0 == status' failed.
```
Do you have an idea of why this is the case?

**Comment by jeffdaily** [comment]
Hi - back from holiday now.  Hopefully we can fix this now.

That line of code is in the following function (failure indicated toward the end):

```C
int comex_init()
{
    int status;
    int init_flag;

    if (initialized) {
        return COMEX_SUCCESS;
    }
    initialized = 1;

    /* Assert MPI has been initialized */
    status = MPI_Initialized(&init_flag);
    assert(MPI_SUCCESS == status);
    assert(init_flag);

    /* Duplicate the World Communicator */
    status = MPI_Comm_dup(MPI_COMM_WORLD, &(l_state.world_comm));
    assert(MPI_SUCCESS == status); /* <----- FAILURE */
    assert(l_state.world_comm);
```

The MPI_Comm_dup() is failing.  I do not know why.  The previous part of that function asserts that MPI_Initialized() is true.  The code above is not reporting the exact error code, just the assert.  I haven't seen this kind of error before.  Did you make any progress in the meantime?

**Comment by mkhoshle** [comment]
Hi, No unfortunately. When I install mpich and gfortran I get the above error. When I use package manager and I load mpich and gfortran inside my virtual environment I get the following error:
```
python: src-mpi/comex.c:1373: comex_init: Assertion `init_flag' failed.
Aborted
```
Which is in `assert(init_flag)` and I do not understand why this is the case!

**Comment by mkhoshle** [comment]
I managed to install it! The problem was with managing my dependencies. So I close this issue!

**Comment by jeffdaily** [comment]
Glad to hear it!  Let us know how else we might help you in the future.

**Comment by mkhoshle** [comment]
Sure, Thank you!
